# Generated by Django 6.0.1 on 2026-02-06 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('weight', models.FloatField()),
                ('is_female', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added'],
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('jump_height', models.FloatField()),
                ('reacts_to_name', models.BooleanField()),
                ('steals_food', models.BooleanField()),
                ('is_orange_cat', models.BooleanField()),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('does_fetch', models.BooleanField()),
                ('knows_how_to_sit', models.BooleanField()),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('speed', models.FloatField()),
                ('is_race_horse', models.BooleanField()),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('eats_carrots', models.BooleanField()),
            ],
            bases=('pets.pet',),
        ),
    ]
